# Numpy functions on multi-dimensional arrays

In [2]:
# initialization
import numpy as np

## Array creation and reshaping

Functions such as `np.zeros()` and `np.full()` can be used to create multi-dimensional arrays. The only change is that instead of supplying the size as a scalar, we specify the shape of the output. For example:

In [4]:
np.zeros((3,4,2)) # 3 sheets, 4 rows, 2 columns

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [5]:
np.full((3, 4), 1) # 3 rows, 4 columns, value = 1

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

More generally, we can create a 1D array, and then reshape it into the desired shape. This can be achieved using the `.reshape()` method. An example:

In [10]:
np.arange(12).reshape((3, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Note that when we reshape, values increment happened first to the last dimensions, then work its way up.

The reverse of `.reshape()` is `.flatten()`, e.g.,

In [12]:
x = np.array([[1, 3, 5, 7], [2, 4, 6, 8]])
x.flatten()

array([1, 3, 5, 7, 2, 4, 6, 8])

Finally, sometimes we want to exchange the rows and columns of a numpy array. Such operation is known as "transposition" and can be achieved using the `.transpose()` method

In [13]:
x.transpose()

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

## Mapping functions

The mapping functions in numpy can also be applied to multi-dimensional array. The result is somewhat expected: the mapping is applied element-wise and the output array has the same dimension as the input array. Example:

In [15]:
angles = np.array([
    [0, np.pi / 6, np.pi/3, np.pi / 2],
    [-np.pi, -4 * np.pi /3, -5 * np.pi / 3, -2 * np.pi]
])

np.round(np.sin(angles), 3)

array([[ 0.   ,  0.5  ,  0.866,  1.   ],
       [-0.   ,  0.866,  0.866,  0.   ]])

## Reduction functions

By default, reduction function will reduce a multi-dimensional array to a scalar, e.g.,

In [16]:
x = np.array([[1, 3, 5, 7], [2, 4, 6, 8]])
np.max(x)

8

However, more interesting (and useful) behavior can be obtained by supplying the `axis` argument, which tells numpy which dimension should the reduction be applied on.

For example, setting `axis=0` for a 2D array will apply the reduction on the first dimension, i.e., row:

In [17]:
np.max(x, axis=0)

array([2, 4, 6, 8])

Whereas setting `axis=1` for a 1D array will apply the reduction on the second dimension, i.e., column:

In [18]:
np.max(x, axis=1)

array([7, 8])

The idea also applies to 3D arrays, where `axis=0` corresponds to sheets, `axis=1` corresponds to rows, and `axis=2` corresponds to column:

In [19]:
y = np.array([
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8]
    ],[
        [-2, -1, 1, 2],
        [-4, -3, 3, 4]
    ],[
        [0, 1, 0, 1],
        [1, 1, 0, 0]
    ]
    
])

In [21]:
np.mean(y, axis=2)

array([[2.5, 6.5],
       [0. , 0. ],
       [0.5, 0.5]])

You can also apply reduction across multiple axes at once. For example, we can compute the average over both rows and columns for each sheet:

In [23]:
np.mean(y, axis=(1,2))

array([4.5, 0. , 0.5])